// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMN8Vco3yV1MxtQUjri6JrAfFwwNQ6hac',
    appId: '1:579486454887:android:5b6e70554dd776c5bd30c2',
    messagingSenderId: '579486454887',
    projectId: 'one-meal-day',
    storageBucket: 'one-meal-day.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc8dTPqY0QLA87b8OCha4kYcMn9Hr0gJw',
    appId: '1:579486454887:web:b49afb1609640c37bd30c2',
    messagingSenderId: '579486454887',
    projectId: 'one-meal-day',
    authDomain: 'one-meal-day.firebaseapp.com',
    storageBucket: 'one-meal-day.firebasestorage.app',
    measurementId: 'G-2CL7BVV1D8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuFZ_aN3QqLeBsFy3KOsMSG3et39CfFgQ',
    appId: '1:579486454887:ios:d12ffa0cab228396bd30c2',
    messagingSenderId: '579486454887',
    projectId: 'one-meal-day',
    storageBucket: 'one-meal-day.firebasestorage.app',
    iosBundleId: 'com.example.onemealaday2323',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuFZ_aN3QqLeBsFy3KOsMSG3et39CfFgQ',
    appId: '1:579486454887:ios:d12ffa0cab228396bd30c2',
    messagingSenderId: '579486454887',
    projectId: 'one-meal-day',
    storageBucket: 'one-meal-day.firebasestorage.app',
    iosBundleId: 'com.example.onemealaday2323',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBc8dTPqY0QLA87b8OCha4kYcMn9Hr0gJw',
    appId: '1:579486454887:web:d4a60e244ed2c9efbd30c2',
    messagingSenderId: '579486454887',
    projectId: 'one-meal-day',
    authDomain: 'one-meal-day.firebaseapp.com',
    storageBucket: 'one-meal-day.firebasestorage.app',
    measurementId: 'G-KKT1T3W5QG',
  );

}